///<reference types= "Cypress"/>

const { rgb } = require("color-convert")

before(()=>{
   console.log('running my tests')
})

beforeEach(()=>{
  cy.visit('https://www.hsbc.co.in/')
})

it('Google Search',()=>{
  cy.viewport(550, 750)
  cy.get('[name="app-img"]').should('exist')
  cy.title().should('eq', "HSBC India - Credit Cards, NRI Services, Saving and Deposit")
  cy.get('.header-mobile-top > .primary-button > .selected-item').click()
  cy.get('.col-sm-12 > .pull-left > span').should('exist')
  cy.get(':nth-child(5) > .col-sm-12').should('exist')
  cy.get(':nth-child(5) > .col-sm-12').should('be.visible') .and ('not.be.disabled')
  cy.get('[id="username"]').type("abc@xyz.com")
  cy.get('[name="continue"]').should('be.enabled')
  cy.get('[id="rememberMe"]').should('not.be.checked')
  cy.get('[id="username_help_link"]').should('exist')
  cy.get('[id="username_help_link"]').click({force: true})
  cy.get('.t25l > span').should('exist')
  cy.get('[id="Close_dob_exception"]').should('exist')
  cy.get('[id="Close_dob_exception"]').click()
})

it('Google Search',()=>{
  cy.scrollTo('bottom')
  cy.get('nav > .footer-large > :nth-child(2) > a').click()
  cy.url().should('include', '/ways-to-bank/branches/')
  cy.get('.A-TYP38L-RW-ALL').should('exist')
  cy.get('[id="content_main_button_1"]').click()
  cy.get('[id="searchInput"]').type('India',{force:true})
  cy.wait(5000)
  cy.get('[id="searchInput"]').type('{backspace}')
  cy.wait(2000)
  cy.get('[id="autocomplete-results"]').contains('India').click()
  cy.get('.S4y5MRLMz5P7VsczpZwj > :nth-child(3)').should('include.text','Rajbhavan Road')
  cy.get('[class="A-BTN dyDtMFJhIxIve49jQf34 F2AanyfgyiGzuY7KkfBN"]').click()
  cy.get(':nth-child(2) > .S4y5MRLMz5P7VsczpZwj > .RGdv28Je743np867Aqn2 > .mPJtUlFpHpAioQtHYTUY > .yWQITJvVOSElgOOsYgyM').should('have.css','background-color','rgb(219, 0, 17)')
  cy.scrollTo('bottom')
  cy.get('.social-icon-instagram',{timeout: 6000}).should('have.attr','href',"https://instagram.com/hsbc_in/")
  cy.get('.social-icon-facebook',{timeout: 6000}).should('have.attr','href','https://www.facebook.com/HSBCIndia/')
  cy.get('.social-icon-twitter',{timeout: 6000}).should('have.attr','href','https://www.twitter.com/HSBC_IN')
  cy.get('.social-icon-youtube',{timeout: 6000}).should('have.attr','href','https://www.youtube.com/channel/UC3Nt_U6gzLlKdAL9Evq0KXQ/featured') 
  cy.get('.header-logo').click({force:true})
  cy.wait(6000)
  //cy.title().should('eq','HSBC India - Credit Cards, NRI Services, Saving and Deposit')
  cy.scrollTo('bottom')
  cy.get('.lg-7 > .footer-supplementary > :nth-child(3) > a').click()
  cy.xpath('//*[@id="content_intro_hero_no_image_1"]/h1').should('include.text','Privacy Statement')
})

it('Google Search',()=>{
  cy.get('.header-main-navigation-title').contains('Banking').trigger('mouseover')
  cy.contains('Credit Cards').should('have.attr','href','https://www.hsbc.co.in/credit-cards/').click({force: true})
  cy.xpath('//*[@id="listing_intro_hero_banner_2"]/div/h1').should('include.text','Credit cards')
  cy.get('[id="listing_intro_button_1"]').should('exist')
  cy.get('.A-LNKND38L-RW-ALL').should('have.length','3')
  cy.get('[id="listing_main_image_3"]').first().should('have.attr', 'alt', 'HSBC Visa Cashback Credit Card')
  cy.get('.A-LNKND38L-RW-ALL').first().should('include.text', 'HSBC Cashback Credit Card')
  cy.get('[id="listing_main_button_1"]').should('include.text', 'Compare cards').should('exist')
  cy.get('[id="listing_main_button_2"]').should('include.text', 'Find out more').should('exist')
  cy.get('[id="listing_main_button_3"]').should('include.text', 'Apply now').should('exist')
  cy.get('[id="listing_main_button_1"]').click()
  cy.get('.close-button').should('exist')
  cy.get('#title-pp_tools_productComparator_4').should('have.text', 'Select cards to compare')
  cy.get('.label-for-checkbox').should('have.length', 3)
  cy.get('[data-product-type="premier-mastercard-credit-card"] > .container-title-checkbox > .modal-checkbox').click()
  cy.get('[data-product-type="cashback-credit-card"] > .container-title-checkbox > .modal-checkbox').click()
  cy.get('.A-BTNP-RW-ALL').click()
  cy.get('.A-TYPS4L-RW-DEV.title.title-loaded',{timeout: 6000}).should('have.length',2)
  cy.get('.A-TYPS7R-RW-DEV.link-icon.clear-icon').should('have.length',2).should('include.text','Remove card')
  cy.get('.A-TYPS7R-RW-DEV.link-icon.add-icon').eq(0).click({force: true})
  cy.get('[data-product-type="visa-platinum-credit-card"] > .container-title-checkbox > .modal-checkbox').click()
  cy.get('.A-BTNP-RW-ALL').click()
  cy.get('.A-TYPS4L-RW-DEV.title.title-loaded',{timeout: 6000}).should('have.length',3)
  cy.get('.A-TYPS7R-RW-DEV.link-icon.clear-icon').should('have.length',3).should('include.text','Remove card')
  cy.get('.A-TYPS7R-RW-DEV.link-icon.clear-icon').eq(1).click({force: true})
  cy.get('.A-TYPS4L-RW-DEV.title.title-loaded',{timeout: 6000}).should('have.length',2)
  cy.get('.A-TYPS7R-RW-DEV.link-icon.add-icon').eq(0).click({force: true})
  cy.get('.close-button').click()
  cy.on("window:confirm", (t) => {
    expect(t).closeTo()
  })
})